# Guitar Chord Classification Model Inference

In [1]:
import cv2
import numpy as np
from tensorflow.keras.models import load_model

In [3]:
model = load_model('GCDF_chords_classification_model.keras')

In [2]:
def get_available_cameras(max_cams):
    available_cameras = []
    for i in range(max_cams):
        cap = cv2.VideoCapture(i)
        if cap.isOpened():
            available_cameras.append(i)
            cap.release()  
    return available_cameras

available_cams = get_available_cameras(10)

if available_cams:
    print(f"Available cameras: {available_cams}")
else:
    print("No cameras found.")


Available cameras: [0]


In [4]:
import cv2
import numpy as np


cap = cv2.VideoCapture(0)

class_labels = ['G', 'C', 'D', 'F']

zoom_factor = 1.25 # zoom 1.25x into the frame 


while True:
    if not cap.isOpened():
        print("Error: Could not open webcam.")
        break

    ret, frame = cap.read()
    
    if not ret:
        print("Frror: Frame is empty or invalid.")
        break

    # getting dimensions of the frame
    height, width, _ = frame.shape

    # calculating cropping dimensions for zoom
    crop_h = int(height / zoom_factor)
    crop_w = int(width / zoom_factor)
    y1 = (height - crop_h) // 2
    y2 = y1 + crop_h
    x1 = (width - crop_w) // 2
    x2 = x1 + crop_w

    # cropping and resizing back to original dims
    cropped_frame = frame[y1:y2, x1:x2]
    zoomed_frame = cv2.resize(cropped_frame, (width, height), interpolation=cv2.INTER_LINEAR)

    # preprocessing the frame
    img = cv2.resize(zoomed_frame, (384, 384)) / 255.0  # normalize
    img = np.expand_dims(img, axis=0)  # add batch dimension

    predictions = model.predict(img)
    chord = class_labels[np.argmax(predictions)]
    print(predictions)

    cv2.putText(zoomed_frame, f'Chord: {chord}', (10, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('Guitar Chord Detection', zoomed_frame)

    # Exit when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step
[[1.3844502e-07 5.3355044e-01 4.6644798e-01 1.3800799e-06]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
[[2.2160191e-05 8.2221651e-01 1.7773421e-01 2.7192747e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
[[1.5030577e-04 8.6183059e-01 1.3794698e-01 7.2093222e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
[[1.3009485e-04 2.7383038e-01 7.2593713e-01 1.0239715e-04]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
[[2.1746644e-07 9.3811885e-02 9.0618724e-01 6.5406488e-07]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
[[1.1430639e-03 9.2799020e-01 7.0781998e-02 8.4758052e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
[[0.01525886 0.877509   0.1053411  0.00189094]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
[[0.00366259 0.72607154 0.26505542 0.00521045]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
[[0.7409499  0.02811661 0.13811031 0.09282322]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
[[0.03729694 0.03434115 0.6389116  0.28945035]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
[[0.00814492 0.13403

KeyboardInterrupt: 